name: Build EdgeVoiceTranscriber APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: android-actions/setup-android@v3
      - run: chmod +x gradlew || true
      - run: ./gradlew wrapper
      - run: ./gradlew assembleDebug --no-daemon --stacktrace
      - uses: actions/upload-artifact@v4
        with:
          name: EdgeVoiceTranscriber-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
