name: Build EdgeVoiceTranscriber APK

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .   # run gradle from repo root
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Ensure Gradle Wrapper
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: EdgeVoiceTranscriber-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
